server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080  #配置服务器端口
  servlet:
    context-path: /

spring:
  datasource:  #数据源配置
    url: jdbc:mysql://localhost:3306/dorm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2019212960
    hikari:  #配置连接池
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 180000
      connection-timeout: 60000
  freemarker:
    charset: UTF-8
    suffix: .html
    content-type: text/html
    template-loader-path: classpath:/templates/
    enabled: true
    request-context-attribute: request
    cache: false  #页面不加载缓存,修改即时生效
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:  #启用Rest
      filter:
        enabled: true
  thymeleaf:  #禁用thymeleaf缓存
    cache: false
  servlet:
    multipart:  #配置文件上传相关配置
      max-file-size: 5MB
      max-request-size: 50MB
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java  #重启目录
      exclude: WEB-INF/**
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.dorm.model
  configuration:
    map-underscore-to-camel-case: true



