server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dorm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 2019212960
      hikari:
        minimum-idle: 5
        idle-timeout: 180000
        maximum-pool-size: 10
        auto-commit: true
        pool-name: MyHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
  freemarker:
    charset: UTF-8
    suffix: .html
    content-type: text/html
    template-loader-path: classpath:/templates/
    enabled: true
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.dorm.model
  configuration:
    map-underscore-to-camel-case: true



